server:
  port: 7070

spring:
  cloud.stream:
      kafka.binder:
          brokers: hdsp001:6667,hdsp002:6667,hdsp003:6667
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            commit.interval.ms: 1000
      bindings:
        job-supplier-output:
          destination: job-processor

logging:
  level:
    org.abigballofmud: ${LOGGING_LEVEL:debug}
